---
ID: "5aecd46c-225e-4670-94b4-4057034a8676"
Parent: "0cc83dcb-ec2e-4f2a-b582-58cb29e027c8"
Template: "0cc83dcb-ec2e-4f2a-b582-58cb29e027c8"
Path: /sitecore/templates/Sitecore Cognitive Services/Foundation/SCSDK/Metadata/Enumeration Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{9DD0C8B6-FBCD-4E61-B500-EB1FE2914EE7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180405T015042Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
